language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t smarx/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true smarx/docker-react npm run test


deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "dockerreact"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-032586772106"
  bucket_path: "dockerreact"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  
